import { Request, Response, NextFunction } from "express";
import { JsonWebTokenError, TokenExpiredError } from "jsonwebtoken";
import { verifyToken } from "../utils/jwt";
import { UnauthorizedError, ForbiddenError } from "../utils/AppError";
import { Role, Permission } from "../models/User";

// ─── STEP 1: authenticateJWT ────────────────────────────────────────────────
//
// This middleware runs on every protected route BEFORE the controller.
// It does the following in order:
//   1. Reads the Authorization header
//   2. Checks the "Bearer <token>" format
//   3. Extracts the token string
//   4. Verifies the JWT signature using the secret from .env
//   5. Checks the token has not expired
//   6. Validates that every required claim exists and has the correct type
//   7. Attaches the validated claims to req.user
//   8. Calls next() so the request continues to the controller
//
// If anything fails, it calls next(error) which goes to errorHandler.ts
// and returns a 401 response — the controller is never reached.

export function authenticateJWT(
    req: Request,
    res: Response,
    next: NextFunction
): void {
    try {
        // Step 1 — Read the Authorization header
        const authHeader = req.headers.authorization;

        if (!authHeader) {
            throw new UnauthorizedError(
                "Authorization header is missing. Please provide: Authorization: Bearer <token>"
            );
        }

        // Step 2 — Validate the "Bearer <token>" format
        // The header must start with "Bearer " (with a space after it)
        if (!authHeader.startsWith("Bearer ")) {
            throw new UnauthorizedError(
                "Invalid Authorization format. Expected: Authorization: Bearer <token>"
            );
        }

        // Step 3 — Extract the token (everything after "Bearer ")
        const token = authHeader.slice(7).trim();

        if (!token) {
            throw new UnauthorizedError("Token is missing after Bearer keyword");
        }

        // Step 4 & 5 — Verify signature and expiration
        // verifyToken() throws JsonWebTokenError for bad signature
        // and TokenExpiredError for expired tokens
        const decoded = verifyToken(token);

        // Step 6 — Validate required claims
        // We do NOT trust the payload just because the signature is valid.
        // We explicitly check that each claim exists and has the right type.
        validateClaims(decoded as unknown as Record<string, unknown>);

        // Step 7 — Attach validated claims to req.user
        // Controllers and downstream middleware can now read req.user.userId etc.
        req.user = decoded;

        // Step 8 — Continue to the next middleware or controller
        next();

    } catch (error) {
        // Convert jsonwebtoken library errors into our custom AppError types
        // so errorHandler.ts returns the correct HTTP status code

        if (error instanceof TokenExpiredError) {
            return next(new UnauthorizedError("Token has expired. Please log in again"));
        }

        if (error instanceof JsonWebTokenError) {
            return next(new UnauthorizedError("Invalid token. Signature verification failed"));
        }

        // Re-throw our own UnauthorizedError or any unexpected error
        next(error);
    }
}


// ─── Claims Validator ────────────────────────────────────────────────────────
//
// Validates that the decoded JWT payload contains all required claims
// with the correct datatypes. Called inside authenticateJWT after verifyToken().
//
// Why validate claims separately from signature verification?
// Because a token can have a valid signature but still be missing claims
// if it was generated by a different system or an older version of the code.

function validateClaims(payload: Record<string, unknown>): void {

    // Allowed roles defined by the application
    const allowedRoles: Role[] = [
        "ADMIN",
        "USER"
    ];

    // Allowed permissions defined by the Subject Management service
    const allowedPermissions: Permission[] = [
        "SUBJECT_CREATE",
        "SUBJECT_READ",
        "SUBJECT_UPDATE",
        "SUBJECT_DELETE"
    ];

    // userId — must be a non-empty string
    if (
        !payload.userId ||
        typeof payload.userId !== "string" ||
        payload.userId.trim() === ""
    ) {
        throw new UnauthorizedError(
            "Invalid token: userId claim is missing or not a valid string"
        );
    }


    // tenantId — must be a non-empty string
    if (
        !payload.tenantId ||
        typeof payload.tenantId !== "string" ||
        payload.tenantId.trim() === ""
    ) {
        throw new UnauthorizedError(
            "Invalid token: tenantId claim is missing or not a valid string"
        );
    }

    // roles — must be a non-empty array of strings
    if (
        !Array.isArray(payload.roles) ||
        payload.roles.length === 0 ||
        !payload.roles.every((r) => typeof r === "string")
    ) {
        throw new UnauthorizedError(
            "Invalid token: roles claim is missing or not a valid non-empty array of strings"
        );
    }

    // permissions — must be an array of strings (can be empty for a restricted user)
    if (
        !Array.isArray(payload.permissions) ||
        !payload.permissions.every((p) => typeof p === "string")
    ) {
        throw new UnauthorizedError(
            "Invalid token: permissions claim is missing or not a valid array of strings"
        );
    }
}


// ─── STEP 2: authorizeRole ───────────────────────────────────────────────────
//
// This middleware runs AFTER authenticateJWT on routes that require a specific role.
// It checks whether req.user.roles contains at least one of the allowed roles.
//
// Usage in routes:
//   router.post("/", authenticateJWT, authorizeRole("ADMIN"), controller)
//
// If the user's role is not in the allowed list → 403 Forbidden
// (The user IS authenticated, but is NOT allowed to do this operation)

export function authorizeRole(...allowedRoles: Role[]) {
    return function (req: Request, res: Response, next: NextFunction): void {
        // req.user is guaranteed to exist here because authenticateJWT ran first
        const userRoles = req.user!.roles;

        const hasRole = allowedRoles.some((role) => userRoles.includes(role));

        if (!hasRole) {
            return next(
                new ForbiddenError(
                    `Access denied. Required role: [${allowedRoles.join(", ")}]. Your role: [${userRoles.join(", ")}]`
                )
            );
        }

        next();
    };
}


// ─── STEP 3: authorizePermission ─────────────────────────────────────────────
//
// This middleware runs AFTER authenticateJWT on routes that require a specific permission.
// It checks whether req.user.permissions contains the required permission.
//
// Usage in routes:
//   router.post("/", authenticateJWT, authorizePermission("SUBJECT_CREATE"), controller)
//
// Role vs Permission:
//   Role    = broad category  (ADMIN, USER)
//   Permission = specific action (SUBJECT_CREATE, SUBJECT_READ, ...)
//
// You can use either or both depending on how fine-grained you need the control.

export function authorizePermission(...requiredPermissions: Permission[]) {
    return function (req: Request, res: Response, next: NextFunction): void {
        const userPermissions = req.user!.permissions;

        const hasPermission = requiredPermissions.every((perm) =>
            userPermissions.includes(perm)
        );

        if (!hasPermission) {
            return next(
                new ForbiddenError(
                    `Access denied. Required permission: [${requiredPermissions.join(", ")}]. Your permissions: [${userPermissions.join(", ")}]`
                )
            );
        }

        next();
    };
}
